---
- name: Config Vim with plugins
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ ansible_env.HOME }}/.vimrc"
    coc_ext_dir: "{{ ansible_env.HOME }}/.config/coc/extensions"
  tasks:
    - name: Install required packages
      apt:
        name:
          - vim
          - git

    - name: Ensure .vim/{autoload,bundle} directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"

    - name: Ensure Pathogen is in place
      get_url:
        dest: "{{ vim_dir }}/autoload/pathogen.vim"
        url: https://tpo.pe/pathogen.vim

    - name: Deploy plugins
      git:
        dest: "{{ vim_dir }}/bundle/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: yes
        update: yes
        recursive: no
      loop:
      - name: vim-lightline
        url: https://github.com/itchyny/lightline.vim
      - name: nerdtree
        url: https://github.com/preservim/nerdtree
      - name: vim-polyglot
        url: https://github.com/sheerun/vim-polyglot
      - name: gruvbox
        url: https://github.com/morhetz/gruvbox
      - name: vim-surround
        url: https://github.com/tpope/vim-surround
      - name: vim-commentary
        url: https://github.com/tpope/vim-commentary
      - name: emmet
        url: https://github.com/mattn/emmet-vim
      - name: prettier
        url: https://github.com/prettier/vim-prettier

    - name: Ensure .vimrc config in place
      copy:
        src: vimrc
        dest: "{{ vimrc }}"
        backup: yes
        mode: 0640
